chore: test pre-commit script

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,12 +1,15 @@
-# check if there is any errors
 npm run check
 if [ $? -ne 0 ]; then
   echo "Errors found in the code, please fix them before commiting"
   exit 1
 fi
 
-# format the code
 npm run format
 
-# exit with code 0
+npm run lint
+if [ $? -ne 0 ]; then
+  echo "Errors found in the code, please fix them before commiting"
+  exit 1
+fi
+
 exit 0
